version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  portainer:
    image: portainer/portainer-ce
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Services/Customer/Customer.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile

volumes:
  portainer_data:

